name: Build Docs

on:
  push:
    branches:
      - main

jobs:
  build_vue:
    runs-on: ubuntu-latest
    name: Build Docs
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: yarn
      - run: yarn install --frozen-lockfile

      - name: Build
        run: yarn build && yarn build:docs

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/.island/dist
